# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev 

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
pool:
  name: localcicdagent

stages:
    
- stage: Dockerize
  displayName: Build docker image
  jobs:
  - job: Build
    displayName: Build docker image
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
