name: Gradle Build

on:
  push:
    branches:
      - feature_add_soarqube_to_githubactions
  pull_request:

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: zoozoo
          POSTGRES_DB: authentication
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # - name: Analyse with sonal cloud
      #   run:  ./gradlew -B verify sonar:sonar -Dsonar.projectKey=ProductSyncApp-UserService -Dsonar.organization=rijothedeveloper -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      #   env:
      #     GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      #     SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run tests
        run: ./gradlew test
